<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>marco_demo</name>
  <version>0.1.0</version>
  <description>Flutter kontrollu A/B hareket ve serit takip demosu.</description>
  <maintainer email="marco@marmara.edu.tr">MarCO Yazilim Ekibi</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>action_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>lifecycle_msgs</exec_depend>
  <exec_depend>lane_tracking</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>marco_msgs</exec_depend>
  <exec_depend>marco_navigation</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>python3-rclpy</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>tf2_ros_py</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
